name: neuro_ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - ipython
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - matplotlib
  - nb_conda
  - nb_conda_kernels
  - nbconvert
  - nbformat
  - numpy
  - pandas
  - pip
  - pytest
  - scikit-image
  - scikit-learn
  - nilearn
  - mne
  - scipy
  - seaborn
  - statsmodels
  - pytorch
  - tensorflow
  - traits
  - bokeh
  - plotly
  - pip:
    - joblib
    - nbval
    - nose
    - pingouin
    - RISE
    - jupyter-book